base: '%env(VIRTUAL_HOST_1)%'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=73'
languages:
  -
    title: German
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: German
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
    solr_core_read: '%env(SOLR_CORE_EN)%'
  -
    title: English
    enabled: true
    languageId: 1
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: free
    fallbacks: ''
    flag: us
    websiteTitle: ''
    solr_core_read: '%env(SOLR_CORE_DE)%'
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      yoast-snippetpreview.json: 1480321830
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\n\r\nDisallow: /typo3/\r\nDisallow: /typo3conf/\r\nAllow: /typo3conf/ext/\r\n\r\n# sitemap\r\nSitemap: https://%env(HTTP_HOST)%/sitemap.xml"
  -
    route: humans.txt
    type: staticText
    content: "/* SITE */\r\nSite: https://github.com/t3kit\r\nStandards: HTML5, CSS3, PHP7\r\nComponents: TYPO3 v10, t3kit10, Bootstrap 5"
solr_enabled_read: true
solr_host_read: '%env(SOLR_HOST_MAIN)%'
solr_path_read: /solr/
solr_port_read: '%env(SOLR_PORT)%'
solr_scheme_read: http
solr_use_write_connection: false
theme: t3kit
websiteTitle: t3kit10
